[project]
name = 'Healthcare-Data-Management-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-marketplace]
path = 'contracts/data-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.health-record]
path = 'contracts/health-record.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
